### ISSUE TITLE
Determine which elements to include in header

### ISSUE THREAD

**Issue by skoolbus39** [d-c-n/dcf#15]
How much customization do we want each of us to have over what appears in the header? Is differentiation by logo, brand colors and typography enough? Should all things be formatted similarly?

**Comment by skoolbus39** [comment]
Potential header elements:
- Logo
- Institution name separate from logo?
- Site Title?
- Search
- Primary Navigation
- Secondary Navigation?
- Breadcrumbs in header? Or, in main content, adjacent to page title?
- Login/Identity Management/Dashboard
- Call to action to donate to University of Nebraska Foundation
- Call to action to Apply Now

**Comment by ptryno** [comment]
Just thought I'd share a mock up I made a while ago trying to figure out what to do with our headers. [Nebraska Medicine](https://www.nebraskamed.com/) just went through a site redesign so we're trying to align with them a bit more. We also have some sites, like facilities, that are both UNMC and Nebraska Medicine. None of it has at all been finalized. 

[UNMC header examples](https://drive.google.com/file/d/0B1ue3qDZGiRbUEpuaHd5YmRjZWc/view?usp=sharing)

I still need to talk to our branding team, but Im hoping we don't need to spell out "University of Nebraska Medical Center" on every page and that the UNMC in the top left will be enough. Otherwise these titles will get pretty ugly, especially on mobile.

Also using a secondary navigation for some action items like Apply, Visit, etc. The"Audience" link would be a drop down that would lead you to our current "audience gateway" links that we have on every page. These lead to pages that house resources for those particular audience members. Not sure if "Audience" is the best term to use here or something like "Resources for" but you get the idea.
